#!/bin/bash
# Scans tools/ and domains/ for packages that call core.Register* and generates imports_gen.go.
# Only packages with actual registrations are imported — interface-only packages are excluded.
#
# Usage:
#   bash gen-imports.sh           — regenerate imports_gen.go
#   bash gen-imports.sh --check   — exit 1 if imports_gen.go is stale (for CI / pre-commit)

set -euo pipefail

MODULE=$(head -1 go.mod | awk '{print $2}')

generate() {
  printf '// Code generated by gen-imports.sh; DO NOT EDIT.\npackage main\n\nimport (\n'

  grep -rl "core\.Register" tools domains --include="*.go" 2>/dev/null \
    | grep -v "_test\.go" \
    | while read -r file; do dirname "$file"; done \
    | sort -u \
    | while read -r dir; do
        printf '\t_ "%s/%s"\n' "$MODULE" "$dir"
      done

  printf ')\n'
}

if [ "${1:-}" = "--check" ]; then
  current=$(cat imports_gen.go 2>/dev/null || true)
  expected=$(generate)
  if [ "$current" != "$expected" ]; then
    echo "❌ imports_gen.go is stale. Run: bash gen-imports.sh" >&2
    exit 1
  fi
  echo "✅ imports_gen.go is up to date"
  exit 0
fi

generate > imports_gen.go

echo "✅ imports_gen.go updated:"
cat imports_gen.go
